services:
  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "9192:9191"  # Changed to map internal 9191 to external 9192
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    ports:
      - "9193:9191"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  authentication-service:
    build:
      context: ./authentication-service  # Changed from appointment-service
      dockerfile: Dockerfile
    ports:
      - "9194:9191"  # Changed to avoid port conflict
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  business-service:
    build:
      context: ./business-service  # Changed from appointment-service
      dockerfile: Dockerfile
    ports:
      - "9195:9191"  # Changed to avoid port conflict
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
