spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

graphql:
  graphiql:
    mapping: /graphiql
    enabled: 'true'
    static:
      basePath: /graphiql
  servlet:
    mapping: /graphql

server:
  port: 9191
