spring:
  application:
    name: buisness-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

graphql:
  graphiql:
    mapping: /graphiql
    enabled: 'true'
    static:
      basePath: /graphiql
  servlet:
    mapping: /graphql

server:
  port: 9195

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    instance:
      prefer-ip-address: true  # Use the IP address for registration
